### ISSUE TITLE
Memory leak in Attribute::read

### ISSUE THREAD

**Issue by robomics** [BlueBrain/HighFive#658]
Calling `Attribute::read` results in 4 bytes of memory leaked.

I believe the bug was introduced with `v2.5.0`.

**To Reproduce**
The leak is observable by compiling and running the following code with ASAN (tested with clang 14 and gcc 12.2):
```c++
#include <highfive/H5File.hpp>
#include <string>
#include <cassert>
#include <cstdint>


template <class T>
void compare_attribute(const HighFive::File& f, const std::string& key, const T& expected) {
  T buff{};
  f.getAttribute(key).read(buff);  // Leak occurs here

  assert(expected == buff);
}

template <class T>
void write(HighFive::File& f, const std::string& key, const T& value) {
  [[maybe_unused]] HighFive::SilenceHDF5 silencer{};
  f.createAttribute(key, value);
}


int main(int argc, char** argv) {
  auto f = HighFive::File("test.h5", HighFive::File::Truncate);

  const std::string buff{"abc"};
  
  write(f, "std::string", buff);
  compare_attribute(f, "std::string", buff);
}

```

```
=================================================================
==2900306==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x55b581dc1559 in malloc (/tmp/test/highfive_leak+0xfd559) (BuildId: a3c1fe924fd2136cdc73ce813614afa407a3602f)
    #1 0x55b582352e46 in H5T__vlen_mem_str_write /tmp/.conan/data/hdf5/1.12.2/_/_/build/5c8256b193173b6a729078a54c772ea08fff1c29/source_subfolder/src/H5Tvlen.c:785:34
    #2 0x55b58225850c in H5T__conv_vlen /tmp/.conan/data/hdf5/1.12.2/_/_/build/5c8256b193173b6a729078a54c772ea08fff1c29/source_subfolder/src/H5Tconv.c:3401:29
    #3 0x55b582235a9b in H5T_convert /tmp/.conan/data/hdf5/1.12.2/_/_/build/5c8256b193173b6a729078a54c772ea08fff1c29/source_subfolder/src/H5T.c:5442:14
    #4 0x55b581e574b4 in H5A__read /tmp/.conan/data/hdf5/1.12.2/_/_/build/5c8256b193173b6a729078a54c772ea08fff1c29/source_subfolder/src/H5Aint.c:645:21
    #5 0x55b58238a08b in H5VL__native_attr_read /tmp/.conan/data/hdf5/1.12.2/_/_/build/5c8256b193173b6a729078a54c772ea08fff1c29/source_subfolder/src/H5VLnative_attr.c:171:22
    #6 0x55b582358cf9 in H5VL__attr_read /tmp/.conan/data/hdf5/1.12.2/_/_/build/5c8256b193173b6a729078a54c772ea08fff1c29/source_subfolder/src/H5VLcallback.c:1157:9
    #7 0x55b582358955 in H5VL_attr_read /tmp/.conan/data/hdf5/1.12.2/_/_/build/5c8256b193173b6a729078a54c772ea08fff1c29/source_subfolder/src/H5VLcallback.c:1188:9
    #8 0x55b581e4ce66 in H5Aread /tmp/.conan/data/hdf5/1.12.2/_/_/build/5c8256b193173b6a729078a54c772ea08fff1c29/source_subfolder/src/H5A.c:705:22
    #9 0x55b581e425cf in void HighFive::Attribute::read<char const*>(char const**, HighFive::DataType const&) const /tmp/.conan/data/highfive/2.6.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/highfive/bits/H5Attribute_misc.hpp:96:9
    #10 0x55b581e4007e in void HighFive::Attribute::read<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const /tmp/.conan/data/highfive/2.6.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/highfive/bits/H5Attribute_misc.hpp:77:5
    #11 0x55b581e0a326 in void compare_attribute<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(HighFive::File const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /tmp/test/highfive_leak.cpp:10:23
    #12 0x55b581e086bc in main /tmp/test/highfive_leak.cpp:28:3
    #13 0x7fbef91ba28f  (/usr/lib/libc.so.6+0x2328f) (BuildId: 1e94beb079e278ac4f2c8bce1f53091548ea1584)

SUMMARY: AddressSanitizer: 4 byte(s) leaked in 1 allocation(s).
```

**Desktop (please complete the following information):**
 - OS: archlinux
 - Version: 2.6.2

**Comment by alkino** [comment]
Thanks you for your report, I produced a fix in #660, tested with your small example and ASAN.
The small reproducible help a lot.
